# FILES
alias ls='ls --color=auto'
alias l='ls -lah'

# GIT
alias ga='git add'
alias gst='git status'
alias gp='git push'
alias gl='git pull'
alias gcmsg='git commit -S -m'
alias gco='git checkout'
alias gcl='git clone --recurse-submodules'
alias gtv='git tag | sort -V'
alias gf='git fetch'
alias gm='git merge'
alias gr='git remote'
alias gra='git remote add'
alias grs='git restore'
alias gst='git status'
alias gsta='git stash push'